trigger:
  branches:
    include:
      - main

pool:
  name: 'self-hosted'

variables:
  TF_VAR_pm_user: $(PM_USER)
  TF_VAR_pm_password: $(PM_PASSWORD)
  TF_VAR_vm_username: $(VM_USERNAME)
  TF_VAR_vm_password: $(VM_PASSWORD)

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform --version
        terraform init
        terraform plan
      displayName: 'Terraform Init and Plan'