name: Terraform Plan (Proxmox)

on:
  push:
    paths: ['**.tf', '**.tfvars']
  pull_request:

jobs:
  terraform-plan:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - run: terraform init
      - run: terraform plan -out=tfplan.binary
        env:
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./proxmox-vm/tfplan.binary
