name: Terraform Apply (Proxmox)

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - uses: dawidd6/action-download-artifact@v9
        with:
          workflow: terraform-plan.yml
          workflow_conclusion: success
          name: terraform-plan
          github_token: ${{ secrets.G_TOKEN }}
      - run: terraform init
      - run: terraform apply -auto-approve tfplan.binary
        env:
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}