name: Terraform Plan - Apply (Proxmox)

on:
  push:
    paths: ['**.tf', '**.tfvars']
  pull_request:

jobs:
  terraform-plan:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - run: terraform init
      - run: terraform plan -out=tfplan.binary
        env:
          TF_VAR_pm_user: ${{ secrets.PM_USER }}
          TF_VAR_pm_password: ${{ secrets.PM_PASSWORD }}
          TF_VAR_vm_username: ${{ secrets.VM_USERNAME }}
          TF_VAR_vm_password: ${{ secrets.VM_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan.binary
  